// Static context in one continuous Albers projection; no relocated state insets or runtime tiles.
// Natural Earth is public domain: https://www.naturalearthdata.com/about/terms-of-use/
// US outline: installed us-atlas / US Census cartographic boundaries.
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { geoAlbers, geoAlbersUsa, geoArea, geoBounds, geoPath } from 'd3';
import mapshaper from 'mapshaper';
import { groundColor } from '../src/electionData.js';

const scale = 0.669;
const k = 1300 * scale;
const translate = [487.5 * scale, 305 * scale];
const bounds = [-680, -560, 1620, 1230];
const [x, y, width, height] = bounds;
const projection = geoAlbers().scale(k).translate(translate);
const usa = geoAlbersUsa().scale(k).translate(translate);
// The mainland must align without changing any existing county or camera coordinates.
for (const point of [[-122.3321, 47.6062], [-117.1611, 32.7157], [-83.0458, 42.3314]]) {
  assert.deepEqual(projection(point), usa(point));
}
assert.ok(Math.abs(projection([-122.3321, 47.6062])[0] - 65.31110288727507) < 1e-8);
projection.clipExtent([[x, y], [x + width, y + height]]);
const toPath = geoPath(projection).digits(2);
const base = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson';
const [countries, lakes] = await Promise.all(['ne_50m_admin_0_countries', 'ne_50m_lakes'].map(async (name) => {
  const response = await fetch(`${base}/${name}.geojson`);
  if (!response.ok) throw new Error(`${name}: HTTP ${response.status}`);
  const collection = await response.json();
  assert.equal(collection.type, 'FeatureCollection');
  return collection.features;
}));
const neighbors = countries.filter((feature) => feature.properties.CONTINENT === 'North America'
  && feature.properties.ADMIN !== 'United States of America');
assert.ok(neighbors.some((feature) => feature.properties.ADMIN === 'Canada'));
assert.ok(neighbors.some((feature) => feature.properties.ADMIN === 'Mexico'));
const nearbyLakes = lakes.filter((feature) => {
  const [[west, south], [east, north]] = geoBounds(feature);
  return west > -170 && east < -35 && north > 10 && south < 80;
});
const nationSource = readFileSync(new URL('../node_modules/us-atlas/nation-10m.json', import.meta.url), 'utf8');
// D3 spherical paths expect clockwise exterior rings, unlike RFC 7946.
const nationOutput = await mapshaper.applyCommands('-i nation.json -o target=nation format=geojson gj2008 nation.geojson', { 'nation.json': nationSource });
const nationGeo = JSON.parse(nationOutput['nation.geojson']);
assert.ok(geoArea(nationGeo) < 2 * Math.PI, 'US polygon winding must not fill the rest of the globe');
const nation = toPath(nationGeo);
const paths = (features) => features.map(toPath).filter(Boolean).map((path) => `<path d="${path}"/>`).join('\n');
const labels = [
  ['CANADA', [-114, 55.5], 15, 3, false],
  ['MEXICO', [-102, 25], 15, 2.8, false],
  ['PACIFIC OCEAN', [-126, 36], 12, 2, true],
  ['ATLANTIC OCEAN', [-70, 35], 12, 2, true],
  ['Gulf of Mexico', [-90, 25.5], 12, 0.5, true],
  ['ALASKA', [-151, 64], 13, 2, false],
  ['HAWAII', [-157, 18], 12, 1.5, false],
].map(([name, coordinate, size, spacing, italic]) => {
  const [px, py] = projection(coordinate);
  const label = name.replace(' OCEAN', `<tspan x="${px.toFixed(2)}" dy="15">OCEAN</tspan>`);
  return `<text x="${px.toFixed(2)}" y="${py.toFixed(2)}" font-size="${size}" letter-spacing="${spacing}"${italic ? ' font-style="italic"' : ''}>${label}</text>`;
}).join('\n');
const rect = `x="${x}" y="${y}" width="${width}" height="${height}"`;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${bounds.join(' ')}" width="6480" height="4920">
<!-- Generated by scripts/build-basemap.mjs. Natural Earth 1:50m, public domain: https://www.naturalearthdata.com/ ; US Census outline via us-atlas. -->
<defs>
  <linearGradient id="fade-x"><stop stop-color="white" stop-opacity="0"/><stop offset="8%" stop-color="white"/><stop offset="92%" stop-color="white"/><stop offset="100%" stop-color="white" stop-opacity="0"/></linearGradient>
  <linearGradient id="fade-y" x2="0" y2="1"><stop stop-color="white" stop-opacity="0"/><stop offset="8%" stop-color="white"/><stop offset="92%" stop-color="white"/><stop offset="100%" stop-color="white" stop-opacity="0"/></linearGradient>
  <mask id="horizontal" maskUnits="userSpaceOnUse" ${rect}><rect ${rect} fill="url(#fade-x)"/></mask>
  <mask id="vertical" maskUnits="userSpaceOnUse" ${rect}><rect ${rect} fill="url(#fade-y)"/></mask>
</defs>
<g mask="url(#horizontal)"><g mask="url(#vertical)">
    <rect ${rect} fill="#edf1f2"/>
    <g fill="#f2f0eb" stroke="#c4cdd0" stroke-width="0.75" stroke-linejoin="round">${paths(neighbors)}</g>
    <g fill="#edf1f2">${paths(nearbyLakes)}</g>
  <path d="${nation}" fill="${groundColor}"/>
  <g fill="#596875" font-family="Georgia, serif" text-anchor="middle">${labels}</g>
</g></g>
</svg>\n`;
assert.ok(!svg.includes('NaN') && !svg.includes('d=""'));
writeFileSync(new URL('../public/basemap.svg', import.meta.url), svg);
console.log(`Basemap ${bounds.join(' ')}; ${neighbors.length} countries, ${nearbyLakes.length} lakes; ${(svg.length / 1024).toFixed(0)} KB`);
